### ISSUE TITLE
Can't find extension in marketplace

### ISSUE THREAD

**Issue by bleuge** [maziac/z80-unit-tests#1]
Must I install it manually?

**Comment by maziac** [comment]
Hi,
the extension is not complete yet.
I think I will release it in about a month to the market place.
You will also need to install the dependent extension "z80-debug" which I also plan
update at the same time.

**Comment by bleuge** [comment]
Ok, thanks! I am starting to learn a bit about ZX dev. Thanks!

**Comment by maziac** [comment]
Hi,
this was quicker now than expected:
I released the extension to market place. In order to use it you also need the z80-debug extension v9.0 (and ZEsarUX v8.0 of course).
For color highlighting and other helpful features I recommend that you also install the asm-code-lens extension.

If you are using the unit test feature I would really be interested to get some feedback. I tested it very thoroughly, I think, but there are so many configuration issues involved that something can easily go wrong.

For an example to use unit tests take a look at: https://github.com/maziac/z80-sample-program
and read the documentation at:
https://github.com/maziac/z80-debug/blob/master/documentation/UnitTests.md

Have fun.

**Comment by bleuge** [comment]
Man, you were fast :D I think I'll need time until I start testing, let me learn first how to at least compile and the basic lib. But I did a fast testing with live debugging via ZEsarUX and worked perfectly in a snap. This will be a huge help for me, learning z80 and see how code works, pretty nice. Thanks!
